main.o: main.asm macros.mac
	nasm -f elf64 -g -F dwarf main.asm -l main.lst
input.o: input.asm
	nasm -f elf64 -g -F dwarf input.asm -l input.lst
inrnd.o: inrnd.asm
	nasm -f elf64 -g -F dwarf inrnd.asm -l inrnd.lst
output.o: output.asm
	nasm -f elf64 -g -F dwarf output.asm -l output.lst
modify.o: modify.asm
	nasm -f elf64 -g -F dwarf modify.asm -l modify.lst
gcc -g -o task main.o input.o inrnd.o output.o modify.o -no-pie
